const playersArray=[
  {
    "name": "YOGESH KUMAR",
    "dateOfBirth": "01-01-1995",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "4.59E+11",
    "classification": "All Rounder",
    "roleBowling": "Right Arm Fast Medium",
    "previousTeam": "MARATHA'S",
    "basePrice": "500",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1zAh0OFM7rEeyZluVVXJs2_rNvimvAH32"
  },
  {
    "name": "Arjun pandit( Arpit)",
    "dateOfBirth": "26-03-2002",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "4.22E+11",
    "classification": "Bowler",
    "roleBowling": "leg Spin",
    "previousTeam": "Galaxy 11",
    "basePrice": "200",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1-yypteCJCBoEsXX0QQVtPxnuDjjQWcnU"
  },
  {
    "name": "Adarsh Singh",
    "dateOfBirth": "16-07-2002",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "4.59E+11",
    "classification": "All Rounder",
    "roleBowling": "Right Arm Fast Medium",
    "previousTeam": "",
    "basePrice": "200",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1z8UgVW5eBmFGmGrp9b-wqL3M9z3BQjt7"
  },
  {
    "name": "Harsh Gupta",
    "dateOfBirth": "23-08-2007",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "4.59E+11",
    "classification": "All Rounder",
    "roleBowling": "Right Arm Fast Medium",
    "previousTeam": "Veer maratha",
    "basePrice": "500",
    "outsiders ": "",
    "Under19": "yes",
    "imageLink": "https://drive.google.com/file/d/1jUJFZmaTM-M7cXdTvodgYvCU2R8gz_NJ"
  },
  {
    "name": "Ashish Kumar",
    "dateOfBirth": "11-05-1990",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "4.59E+11",
    "classification": "Batsman",
    "roleBowling": "",
    "previousTeam": "Kesari Xl",
    "basePrice": "200",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1v1EIfo-Wj6f5ijmV1sbwOY4tVhQB-Jbt"
  },
  {
    "name": "Deepak richhariya",
    "dateOfBirth": "03-08-2000",
    "roleBatting": "Opener",
    "UTRNO": "4.59E+11",
    "classification": "Batsman",
    "roleBowling": "Right Arm Fast Medium",
    "previousTeam": "Not play",
    "basePrice": "200",
    "outsiders ": "yes",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/19yuwht1QtESqAwYwu3onRqLloQOgvCCk"
  },
  {
    "name": "Pankaj Yadav",
    "dateOfBirth": "01-01-2004",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "",
    "classification": "All Rounder",
    "roleBowling": "Right Arm Fast Medium",
    "previousTeam": "",
    "basePrice": "500",
    "outsiders ": "yes",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1Tf3dWK31yei02WVO3BBs6VB3ZkkV401l"
  },
  {
    "name": "Niraj Kumar (Nippo)",
    "dateOfBirth": "01-10-1995",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "4.59E+11",
    "classification": "Batsman",
    "roleBowling": "off spin",
    "previousTeam": "Kesri XI",
    "basePrice": "500",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1maAWkSWgKlY0Zu5p1C5wENdDt7cFysql"
  },
  {
    "name": "Abhishek Kumar Singh ",
    "dateOfBirth": "01-01-1997",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "4.59E+11",
    "classification": "All Rounder",
    "roleBowling": "Right Arm Fast Medium",
    "previousTeam": "Mallawan super king",
    "basePrice": "300",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1bU8uoQrEsU8a0ciSb4H0nUL7Mc4k_-__"
  },
  {
    "name": "Javed asghar",
    "dateOfBirth": "20 04 1995",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "4.59E+11",
    "classification": "All Rounder",
    "roleBowling": "Left Arm Fast Medium",
    "previousTeam": "City capitals",
    "basePrice": "200",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/17j0eBHNZEW2wx5zyP7N6aPvyvBsfAVOL"
  },
  {
    "name": "Junaid asghar",
    "dateOfBirth": "01 01 1998",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "4.59E+11",
    "classification": "Batsman",
    "roleBowling": "",
    "previousTeam": "City capital's",
    "basePrice": "200",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/17MrAX7cugaHUQJFHaTF30oJ-hYjzEIJn"
  },
  {
    "name": "Zaydan Mirza ",
    "dateOfBirth": "04-04-2005",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "",
    "classification": "Batsman",
    "roleBowling": "Right Arm Fast Medium",
    "previousTeam": "Fresher ",
    "basePrice": "300",
    "outsiders ": "yes",
    "Under19": "yes",
    "imageLink": "https://drive.google.com/file/d/11YZVwMij9mTT7slN5i39_udSNFPr7pJ4"
  },
  {
    "name": "Anil Kumar",
    "dateOfBirth": "10-12-1993",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "",
    "classification": "All Rounder",
    "roleBowling": "Right Arm Fast Medium",
    "previousTeam": "??????? ?????",
    "basePrice": "500",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1LdYrozpTdG7r0KcM6LgFmzkcNNXcCzde"
  },
  {
    "name": "Bilal ansari ",
    "dateOfBirth": "28-08-1998",
    "roleBatting": "Opener",
    "UTRNO": "",
    "classification": "Batsman",
    "roleBowling": "Right Arm Fast Medium",
    "previousTeam": "",
    "basePrice": "200",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "Invalid URL"
  },
  {
    "name": "Karan kumar",
    "dateOfBirth": "26-05-2006",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "",
    "classification": "All Rounder",
    "roleBowling": "Right Arm Fast Medium",
    "previousTeam": "",
    "basePrice": "200",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/123Yu4pIUEkji8QaeKT3KtcWKS8J8k5NX"
  },
  {
    "name": "Amit yadav ",
    "dateOfBirth": "07-07-1999",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "",
    "classification": "Wicket keeper",
    "roleBowling": "Right Arm Fast Medium",
    "previousTeam": "Captain Indira Gandhi rajkiy mahavidyalay Bangarmau",
    "basePrice": "200",
    "outsiders ": "yes",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1IzqnQYZbNY49aHyFPUsJzZLdGo0wcQlb"
  },
  {
    "name": "Nitesh dwivedi ",
    "dateOfBirth": "14-10-2002",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "4.59E+11",
    "classification": "Wicket keeper",
    "roleBowling": "",
    "previousTeam": "No one",
    "basePrice": "200",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/17fDwAA1BKXIl0a0A51QOtyipGcFUylQL"
  },
  {
    "name": "Avanish Dixit",
    "dateOfBirth": "29-01-1980",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "UPI transaction ID:459084368074",
    "classification": "Bowler",
    "roleBowling": "Left Arm Fast Medium",
    "previousTeam": "Mallawan warrior ",
    "basePrice": "200",
    "outsiders ": "yes",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1G7uJ35OTNy0STiKPp7zU_CKNKEjwaTDP"
  },
  {
    "name": "Arif Khan",
    "dateOfBirth": "04-12-1996",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "12",
    "classification": "All Rounder",
    "roleBowling": "Right Arm Fast Medium",
    "previousTeam": "Mallawan Maratha",
    "basePrice": "500",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "Invalid URL"
  },
  {
    "name": "Laikuddin (ranu)",
    "dateOfBirth": "1.1.80",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "",
    "classification": "All Rounder",
    "roleBowling": "Right Arm Fast Medium",
    "previousTeam": "Yes",
    "basePrice": "300",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "Invalid URL"
  },
  {
    "name": "Mohd hayat",
    "dateOfBirth": "01 01 2012",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "4.59E+11",
    "classification": "All Rounder",
    "roleBowling": "Right Arm Fast Medium",
    "previousTeam": "Galaxy king",
    "basePrice": "200",
    "outsiders ": "",
    "Under19": "yes",
    "imageLink": "https://drive.google.com/file/d/1UNS1EtlS-_qywLju-xJTYsNJ1t6Mlx_u"
  },
  {
    "name": "Mohd Sharik Raja",
    "dateOfBirth": "12-01-2004",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "4.59E+11",
    "classification": "All Rounder",
    "roleBowling": "Right Arm Fast Medium",
    "previousTeam": "Galaxy king",
    "basePrice": "200",
    "outsiders ": "yes",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1ffDoa5R1eQDpKYEhqztc0cHcVODDelhY"
  },
  {
    "name": "Saurabh Tripathi",
    "dateOfBirth": "10-07-1991",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "4.59E+11",
    "classification": "All Rounder",
    "roleBowling": "Right Arm Fast Medium",
    "previousTeam": "kesari XI",
    "basePrice": "200",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1dYhpTm1V6fBglP42ZXCnE4S9KZpbwly0"
  },
  {
    "name": "Ankit Srivastav",
    "dateOfBirth": "15-03-1991",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "4.59E+11",
    "classification": "Batsman",
    "roleBowling": "",
    "previousTeam": "Kesari XI",
    "basePrice": "200",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1xzFv6mVYx-JxzOyOc3AWq7aRnGuS6o8O"
  },
  {
    "name": "Vishal Gupta ",
    "dateOfBirth": "26-07-2002",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "4.59E+11",
    "classification": "Bowler",
    "roleBowling": "Left Arm Fast Medium",
    "previousTeam": "",
    "basePrice": "300",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1OjwsXWKlvyUqYWKRvw-oRVloItXuYnmj"
  },
  {
    "name": "Shailesh Thakur (Shalu)",
    "dateOfBirth": "13-01-1993",
    "roleBatting": "Left Hand batsman",
    "UTRNO": "4.59E+11",
    "classification": "All Rounder",
    "roleBowling": "Left Arm Fast Medium",
    "previousTeam": "Kersari XI",
    "basePrice": "200",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1xuHkN3oCC0PrpcnIEkwEcwP0cdcpaJ09"
  },
  {
    "name": "Aniruddh Patel chima",
    "dateOfBirth": "12061997",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "4.59E+11",
    "classification": "All Rounder",
    "roleBowling": "Right Arm Fast Medium",
    "previousTeam": "No",
    "basePrice": "200",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/19OJPmv50ofPQlW3GhTxEKCL5xXzsBlnW"
  },
  {
    "name": "Manish verma raju",
    "dateOfBirth": "18-11-1996",
    "roleBatting": "Left Hand batsman",
    "UTRNO": "4.59E+11",
    "classification": "Wicket keeper",
    "roleBowling": "Right Arm Fast Medium",
    "previousTeam": "City capital",
    "basePrice": "200",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1kYAQqSEI337TtqdqhgU0F8vW7il8J28E"
  },
  {
    "name": "Divyanshu singh ",
    "dateOfBirth": "22-03-2003",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "4.59E+11",
    "classification": "All Rounder",
    "roleBowling": "Right Arm Fast Medium",
    "previousTeam": "Royal challengers mallawan ",
    "basePrice": "500",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1StrwwkDiXCT5fxN_eevATHnxM1k4DcHI"
  },
  {
    "name": "Saurabh (shahid) ansari",
    "dateOfBirth": "01-01-1988",
    "roleBatting": "Opener",
    "UTRNO": "4.59E+11",
    "classification": "Wicket keeper",
    "roleBowling": "leg Spin",
    "previousTeam": "City capital",
    "basePrice": "200",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1NhhVejDXhCa446SzsZmiclDPuwNaZP6x"
  },
  {
    "name": "MOHD SIRAJ ANSARI ",
    "dateOfBirth": "20-11-1995",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "4.59E+11",
    "classification": "Wicket keeper",
    "roleBowling": "",
    "previousTeam": "Galaxy 11",
    "basePrice": "200",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1ZC0fzVQ1lumjOHimRRHPGkQ2UMxKLtjK"
  },
  {
    "name": "Vishal Singh (Dhoni)",
    "dateOfBirth": "26-07-1997",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "4.23E+11",
    "classification": "All Rounder",
    "roleBowling": "Right Arm Fast Medium",
    "previousTeam": "Kesari 11",
    "basePrice": "500",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1tnaOIDy8SwP9V0o6YNGjHy8-OMYlI1QK"
  },
  {
    "name": "Mohd Sami ",
    "dateOfBirth": "1995",
    "roleBatting": "Middle Order batsman",
    "UTRNO": "4.59E+11",
    "classification": "Wicket keeper",
    "roleBowling": "Right Arm Fast Medium",
    "previousTeam": "Mallawan warriors And galaxy 11",
    "basePrice": "200",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1gebmgcwMKVm2Flzj1oLCxmFXc0tX2nrb"
  },
  {
    "name": "Rijul Singh",
    "dateOfBirth": "21-12-2004",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "0",
    "classification": "Batsman",
    "roleBowling": "Right Arm Fast Medium",
    "previousTeam": "RCB",
    "basePrice": "300",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/10evf1V0Xn2m5nHD9Zqt2WCFeTB8-zFej"
  },
  {
    "name": "Sachin Sharma ",
    "dateOfBirth": "10-05-1998",
    "roleBatting": "Left Hand batsman",
    "UTRNO": "4.23E+11",
    "classification": "All Rounder",
    "roleBowling": "Left Arm Fast Medium",
    "previousTeam": "",
    "basePrice": "200",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1JMuZmvD-26DHlpzMw3HErsuxg_syuXLJ"
  },
  {
    "name": "Nadeem ansari",
    "dateOfBirth": "1/1/195",
    "roleBatting": "Middle Order batsman",
    "UTRNO": "",
    "classification": "All Rounder",
    "roleBowling": "Right Arm Fast Medium",
    "previousTeam": "",
    "basePrice": "500",
    "outsiders ": "yes",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/10Xg7fC5TN7fSR28LesOiCVa95Tytm3Lt"
  },
  {
    "name": "Dharenarma",
    "dateOfBirth": "1999",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "Oj",
    "classification": "All Rounder",
    "roleBowling": "Right Arm Fast Medium",
    "previousTeam": "Mallwan ",
    "basePrice": "200",
    "outsiders ": "",
    "Under19": "yes",
    "imageLink": "Invalid URL"
  },
  {
    "name": "Mukesh Patel ",
    "dateOfBirth": "28.12.2006",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "",
    "classification": "Bowler",
    "roleBowling": "Left Arm Fast Medium",
    "previousTeam": "",
    "basePrice": "",
    "outsiders ": "yes",
    "Under19": "yes",
    "imageLink": "Invalid URL"
  },
  {
    "name": "Asif ",
    "dateOfBirth": "22-03-1991",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "4.59E+11",
    "classification": "All Rounder",
    "roleBowling": "Right Arm Fast Medium",
    "previousTeam": "",
    "basePrice": "500",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1Jt6g19ZUOJSZ1YIOtkrQZ1z3BPgJ0cyR"
  },
  {
    "name": "RAVINS YADAV",
    "dateOfBirth": "10-01-2001",
    "roleBatting": "Left Hand batsman",
    "UTRNO": "4.59E+11",
    "classification": "Bowler",
    "roleBowling": "Left Arm Fast Medium",
    "previousTeam": "DABANG HEROES",
    "basePrice": "200",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1T7fWuZ-qPKg7QF-jaJj6EVHBysGj6c3i"
  },
  {
    "name": "Shivam singh",
    "dateOfBirth": "01-07-2001",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "",
    "classification": "All Rounder",
    "roleBowling": "Right Arm Fast Medium",
    "previousTeam": "",
    "basePrice": "500",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1supyyACy52tNtrd7JYUKDVXqTXqlDGCL"
  },
  {
    "name": "Rihan ali",
    "dateOfBirth": "15-05-1999",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "",
    "classification": "Wicket keeper",
    "roleBowling": "",
    "previousTeam": "",
    "basePrice": "200",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1SWuBCfDVG7fTFlf_y9SJKceUiSihEOyT"
  },
  {
    "name": "Mufish ahmed ",
    "dateOfBirth": "90,22,002",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "4.59E+11",
    "classification": "All Rounder",
    "roleBowling": "Right Arm Fast Medium",
    "previousTeam": "Keshari 11",
    "basePrice": "500",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1yeMeOXRUOf2pI6_nSzhVFKmp3etO0I2S"
  },
  {
    "name": "Gaurav Verma ",
    "dateOfBirth": "30-04-1991",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "",
    "classification": "Bowler",
    "roleBowling": "Left Arm Fast Medium",
    "previousTeam": "Royal challengers beavers ",
    "basePrice": "500",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1QKM-CEoVjc4zhvgTBVhChlhzXLSoiPqL"
  },
  {
    "name": "Abhishek mishra",
    "dateOfBirth": "08-10-1998",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "4.59E+11",
    "classification": "All Rounder",
    "roleBowling": "Right Arm Fast Medium",
    "previousTeam": "Lucknow University ",
    "basePrice": "300",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1Wp6xkf4Je7o1W7bqlJNA1A99lDEhWIhj"
  },
  {
    "name": "Sumit Pratap Singh (Gole)",
    "dateOfBirth": "01-07-1994",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "",
    "classification": "All Rounder",
    "roleBowling": "Left Arm Fast Medium",
    "previousTeam": "",
    "basePrice": "200",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1bB6c_8HaD5-nQO3qdEKWWjKGNUthuVGp"
  },
  {
    "name": "Arav Patel",
    "dateOfBirth": "17-06-2002",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "4.59E+11",
    "classification": "All Rounder",
    "roleBowling": "Right Arm Fast Medium",
    "previousTeam": "Shivaji warriors ",
    "basePrice": "200",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1V9JkQcsp75Un8P7S6_PL5p6hIXTnffVy"
  },
  {
    "name": "Haider ",
    "dateOfBirth": "03-03-1993",
    "roleBatting": "Left Hand batsman",
    "UTRNO": "",
    "classification": "All Rounder",
    "roleBowling": "Left Arm Fast Medium",
    "previousTeam": "No ",
    "basePrice": "500",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/14A0GCIuTy1Oe7xsjehkkt9QJclBGjTAs"
  },
  {
    "name": "Ramji kashyap ",
    "dateOfBirth": "16-07-1996",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "",
    "classification": "All Rounder",
    "roleBowling": "Right Arm Fast Medium",
    "previousTeam": "Pahuntera cricket team ",
    "basePrice": "500",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1Jo-YBpG9t250AFk5jr23t-oqIfQ3UeK1"
  },
  {
    "name": "Krishna patel",
    "dateOfBirth": "26-12-2007",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "4.23E+11",
    "classification": "All Rounder",
    "roleBowling": "leg Spin",
    "previousTeam": "RCB ",
    "basePrice": "200",
    "outsiders ": "",
    "Under19": "yes",
    "imageLink": "https://drive.google.com/file/d/1isYAuNRkP9mucYAnRxhPGfFFRtd4A0poJe5zAGrr2ek"
  },
  {
    "name": "DILEEP RATHOR",
    "dateOfBirth": "12-07-2001",
    "roleBatting": "Left Hand batsman",
    "UTRNO": "",
    "classification": "All Rounder",
    "roleBowling": "Left Arm Fast Medium",
    "previousTeam": "",
    "basePrice": "",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1MaGjTFnP2pvuYTnOT3Vlv8lDo0K0wlJR"
  },
  {
    "name": "Prince patel",
    "dateOfBirth": "05-07-2008",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "4.59E+11",
    "classification": "Batsman",
    "roleBowling": "off spin",
    "previousTeam": "",
    "basePrice": "200",
    "outsiders ": "",
    "Under19": "yes",
    "imageLink": "Invalid URL"
  },
  {
    "name": "Rudra Pratap Chandel",
    "dateOfBirth": "O5/03/2003",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "4.59E+11",
    "classification": "All Rounder",
    "roleBowling": "Left Arm Fast Medium",
    "previousTeam": "",
    "basePrice": "200",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1UriPQLfam4cKk4cWWZR_6cujqCHjOe9Q"
  },
  {
    "name": "Lavish patel",
    "dateOfBirth": "13-12-2004",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "4.59E+11",
    "classification": "All Rounder",
    "roleBowling": "Right Arm Fast Medium",
    "previousTeam": "Veer maratha",
    "basePrice": "200",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1BipI8SZB6k9eluss5aHQoUgW4Nonz8He"
  },
  {
    "name": "Manmohan Singh",
    "dateOfBirth": "03-10-1997",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "4.23E+11",
    "classification": "Bowler",
    "roleBowling": "Right Arm Fast Medium",
    "previousTeam": "Dabang Heroes , Mallawan Indians , Sahara Cricket UP",
    "basePrice": "200",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1c1LI4nY1a-bngLo7PDXemNOzvue6jTp7"
  },
  {
    "name": "Siddhant Shekhawat ",
    "dateOfBirth": "05-06-1999",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "4.59E+11",
    "classification": "Wicket keeper",
    "roleBowling": "",
    "previousTeam": "Veer Maratha ",
    "basePrice": "300",
    "outsiders ": "yes",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1W6A1lw3LdqK7PNt73lb0PxEgRr_i6B3b"
  },
  {
    "name": "Dheerendra kumar",
    "dateOfBirth": "16-08-2003",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "",
    "classification": "Batsman",
    "roleBowling": "off spin",
    "previousTeam": "New team",
    "basePrice": "200",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1RPvjUuxwXpxPjC_RqxuwN2U9ditmy3Yu"
  },
  {
    "name": "Mohd Anas ",
    "dateOfBirth": "2000",
    "roleBatting": "",
    "UTRNO": "4.59E+11",
    "classification": "Batsman",
    "roleBowling": "",
    "previousTeam": "No Team ",
    "basePrice": "200",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1dSRy6H46EKwwYBB9PXEa0SGsxqY7KIbA"
  },
  {
    "name": "Shisht Dwivedi ",
    "dateOfBirth": "1012007",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "4.59E+11",
    "classification": "All Rounder",
    "roleBowling": "Right Arm Fast Medium",
    "previousTeam": "Success cricket academy hardoi ",
    "basePrice": "300",
    "outsiders ": "",
    "Under19": "yes",
    "imageLink": "https://drive.google.com/file/d/1VlWq4NAHhgle64bONpvOu8zcdmGk4BXR"
  },
  {
    "name": "Jagjeet Singh(Sonu)",
    "dateOfBirth": "17.10.1995",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "4.59E+11",
    "classification": "All Rounder",
    "roleBowling": "Right Arm Fast Medium",
    "previousTeam": "Dabang heros",
    "basePrice": "500",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1PeSeNIMg-Alzs77B1tAP-sEyo2j0ayAo"
  },
  {
    "name": "Anshul Verma ",
    "dateOfBirth": "17-07-2004",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "4.59E+11",
    "classification": "Batsman",
    "roleBowling": "",
    "previousTeam": "",
    "basePrice": "200",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1F2VlVP4S-T_SRb3SMzbHum5qRGl_ggGQ"
  },
  {
    "name": "Satendra pratap singh",
    "dateOfBirth": "14-05-1998",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "9794616997",
    "classification": "All Rounder",
    "roleBowling": "Right Arm Fast Medium",
    "previousTeam": "Indra gandhi rajkiya mahavidyalay bangarmau unnao (under university 3years, 1time man of the match) ",
    "basePrice": "500",
    "outsiders ": "yes",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1Z3NjbQTY3Y9Xip5aYrL7cTUBtOi4g_ki"
  },
  {
    "name": "Trilochan Yadav",
    "dateOfBirth": "08-04-2004",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "4.59E+11",
    "classification": "Batsman",
    "roleBowling": "Right Arm Fast Medium",
    "previousTeam": "",
    "basePrice": "200",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1gwiReOa0lMMmABEJ39IAkm6ozxbly33e"
  },
  {
    "name": "Sudeep Yadav",
    "dateOfBirth": "24-12-1998",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "9415779673",
    "classification": "Batsman",
    "roleBowling": "",
    "previousTeam": "City Capitals",
    "basePrice": "200",
    "outsiders ": "yes",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1pRBpGM_90oLznh-W92xj3WlcW51S__9A"
  },
  {
    "name": "Yogendra Yadav ",
    "dateOfBirth": "05-03-2000",
    "roleBatting": "Left Hand batsman",
    "UTRNO": "4.59E+11",
    "classification": "All Rounder",
    "roleBowling": "Left Arm Fast Medium",
    "previousTeam": "Titan",
    "basePrice": "200",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1pFAD2prHccZavP7eUwiKdfiLS3wHO6ui"
  },
  {
    "name": "Yuvraj Yadav",
    "dateOfBirth": "2001",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "4.23E+11",
    "classification": "All Rounder",
    "roleBowling": "Right Arm Fast Medium",
    "previousTeam": "Veer Maratha",
    "basePrice": "500",
    "outsiders ": "yes",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1-W6fA2cT9BITSi8GobFkGkQebsJUn7-b"
  },
  {
    "name": "Praveen Kumar",
    "dateOfBirth": "10-08-2010",
    "roleBatting": "Left Hand batsman",
    "UTRNO": "4.59E+11",
    "classification": "All Rounder",
    "roleBowling": "Left Arm Fast Medium",
    "previousTeam": "Galaxy ",
    "basePrice": "200",
    "outsiders ": "",
    "Under19": "yes",
    "imageLink": "https://drive.google.com/file/d/13Lt6p7USj9Y78rNJ0gvHDbGvldlqmfnV"
  },
  {
    "name": "Suraj kumar",
    "dateOfBirth": "12-04-2005",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "4.59E+11",
    "classification": "All Rounder",
    "roleBowling": "Right Arm Fast Medium",
    "previousTeam": "No one",
    "basePrice": "200",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1_mgnXJ1IttEuxiu8dzoGLOymYQ7z7T2P"
  },
  {
    "name": "Atul Kumar",
    "dateOfBirth": "10-04-2001",
    "roleBatting": "Left Hand batsman",
    "UTRNO": "4.23E+11",
    "classification": "All Rounder",
    "roleBowling": "Left Arm Fast Medium",
    "previousTeam": "",
    "basePrice": "300",
    "outsiders ": "yes",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/14ZVlcO1k04Mflj7KZUrJWkzLqRZN_JkI"
  },
  {
    "name": "Suraj kumar ",
    "dateOfBirth": "04-09-1998",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "7",
    "classification": "All Rounder",
    "roleBowling": "Right Arm Fast Medium",
    "previousTeam": "Mallawan Dabang",
    "basePrice": "200",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1pi-VbmJiSTbf66olWXwOgDVpXGPlNH1t"
  },
  {
    "name": "Dharmendra ",
    "dateOfBirth": "10 01 1999",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "7398877519",
    "classification": "All Rounder",
    "roleBowling": "Right Arm Fast Medium",
    "previousTeam": "",
    "basePrice": "300",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1TzbK5v6wpyDJADaly12cK0tCeHg8VI2Q"
  },
  {
    "name": "Maan singh",
    "dateOfBirth": "01-08-1996",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "4.23E+11",
    "classification": "All Rounder",
    "roleBowling": "Right Arm Fast Medium",
    "previousTeam": "Dabang Heros",
    "basePrice": "500",
    "outsiders ": "yes",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1E8C8yacIDgFS4JgjLcLMTRa6Tg5tzI_4"
  },
  {
    "name": "Ashu Yadav",
    "dateOfBirth": "04-02-2007",
    "roleBatting": "Left Hand batsman",
    "UTRNO": "4.23E+11",
    "classification": "All Rounder",
    "roleBowling": "Left Arm Fast Medium",
    "previousTeam": "Dabang Heros ",
    "basePrice": "500",
    "outsiders ": "yes",
    "Under19": "yes",
    "imageLink": "https://drive.google.com/file/d/1MemAIRxbR7eMe3fusKOPTST6_zabercO"
  },
  {
    "name": "Neeraj ",
    "dateOfBirth": "12-07-2006",
    "roleBatting": "Middle Order batsman",
    "UTRNO": "4.23E+11",
    "classification": "All Rounder",
    "roleBowling": "leg Spin",
    "previousTeam": "New player ",
    "basePrice": "300",
    "outsiders ": "yes",
    "Under19": "yes",
    "imageLink": "https://drive.google.com/file/d/1azM_ZdG2SH9X-HNQ8ezHLmP4i3tJ-XSS"
  },
  {
    "name": "Yogendra singh ( Monti)",
    "dateOfBirth": "27-07-1996",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "4.59E+11",
    "classification": "Wicket keeper",
    "roleBowling": "",
    "previousTeam": "Galaxy kings 11",
    "basePrice": "300",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1lPhlMGBRjs14qk0sU62c9kpQHybE26SA"
  },
  {
    "name": "AjayKumar ",
    "dateOfBirth": "1997",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "",
    "classification": "All Rounder",
    "roleBowling": "Right Arm Fast Medium",
    "previousTeam": "",
    "basePrice": "500",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1Vu8mfPOkCh_Q39nDYe_FXRS3EM1nGGsV"
  },
  {
    "name": "Naushad alam",
    "dateOfBirth": "11-07-1985",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "4.59E+11",
    "classification": "All Rounder",
    "roleBowling": "off spin",
    "previousTeam": "Mallawan capitals",
    "basePrice": "200",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1sWGffPBfKC-5N77s7_AzPfjZBDOwKBwL"
  },
  {
    "name": "Uday Pratap Singh",
    "dateOfBirth": "03-10-2006",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "4.59E+11",
    "classification": "All Rounder",
    "roleBowling": "Right Arm Fast Medium",
    "previousTeam": "",
    "basePrice": "200",
    "outsiders ": "yes",
    "Under19": "yes",
    "imageLink": "https://drive.google.com/file/d/1C5GtBO3BcNEe_ZSk0ujXAy4Lk2u8m-Eu"
  },
  {
    "name": "Renchu ",
    "dateOfBirth": "07/14/2005",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "4.59E+11",
    "classification": "All Rounder",
    "roleBowling": "leg Spin",
    "previousTeam": "",
    "basePrice": "200",
    "outsiders ": "",
    "Under19": "yes",
    "imageLink": "Invalid URL"
  },
  {
    "name": "Amit Kumar Yadav",
    "dateOfBirth": "15-08-1994",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "4.59E+11",
    "classification": "Bowler",
    "roleBowling": "Right Arm Fast Medium",
    "previousTeam": "",
    "basePrice": "200",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/106F3R8IvgCuUiP_c14vdrzGqmjCHaQUr"
  },
  {
    "name": "Munendra Kumar",
    "dateOfBirth": "02-07-2003",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "4.59E+11",
    "classification": "All Rounder",
    "roleBowling": "Right Arm Fast Medium",
    "previousTeam": "No",
    "basePrice": "200",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1c6OJfYvQoOtCeBXizFNsc_p8YzlcsIxF"
  },
  {
    "name": "Danish Subhaan",
    "dateOfBirth": "31-08-1998",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "5.49E+11",
    "classification": "All Rounder",
    "roleBowling": "Right Arm Fast Medium",
    "previousTeam": "City Capitals",
    "basePrice": "200",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1_fVyfheQ7QJ4ivm-RYaHOaaBmmt_7A9W"
  },
  {
    "name": "Vikash Yadav ",
    "dateOfBirth": "17-08-2006",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "",
    "classification": "Batsman",
    "roleBowling": "off spin",
    "previousTeam": "Dabangg heroes ",
    "basePrice": "500",
    "outsiders ": "",
    "Under19": "yes",
    "imageLink": "https://drive.google.com/file/d/1ZVyUExdUjJL-R0ofdvDqgd7ghJjUNETk"
  },
  {
    "name": "Mohd Faishal Ansari",
    "dateOfBirth": "12-06-1994",
    "roleBatting": "",
    "UTRNO": "4.59E+11",
    "classification": "Bowler",
    "roleBowling": "Right Arm Fast Medium",
    "previousTeam": "City Capitals",
    "basePrice": "200",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/16UcfVeudHPKRH-7r6F721vOTkSp3RGfJ"
  },
  {
    "name": "Sanu Verma ",
    "dateOfBirth": "10-07-2000",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "4.59E+11",
    "classification": "Batsman",
    "roleBowling": "",
    "previousTeam": "",
    "basePrice": "200",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/17MmQcCjiREamJlDrVuaeXtm0Ra3AwQ7W"
  },
  {
    "name": "Ayush Prajapati ",
    "dateOfBirth": "11-04-2009",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "4.59E+11",
    "classification": "Batsman",
    "roleBowling": "leg Spin",
    "previousTeam": "No1",
    "basePrice": "200",
    "outsiders ": "",
    "Under19": "yes",
    "imageLink": "https://drive.google.com/file/d/1O7Rlj0CvRfj1OkEhKjAmbaZxR6zET_VO"
  },
  {
    "name": "Ajay Kumar ",
    "dateOfBirth": "1997",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "4.59E+11",
    "classification": "All Rounder",
    "roleBowling": "Right Arm Fast Medium",
    "previousTeam": "Fresher",
    "basePrice": "300",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1gMsjwqg7pTxpLKQzv4hAh3Z2tApMiJJ6"
  },
  {
    "name": "Mohd. Noman",
    "dateOfBirth": "01-01-2008",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "4.59E+11",
    "classification": "Batsman",
    "roleBowling": "",
    "previousTeam": "",
    "basePrice": "200",
    "outsiders ": "",
    "Under19": "yes",
    "imageLink": "https://drive.google.com/file/d/10RwFh_jcC1vG2kOagf_5ULmu77S9UFiP"
  },
  {
    "name": "Rahul Verma ",
    "dateOfBirth": "04-10-1993",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "4.59E+11",
    "classification": "Batsman",
    "roleBowling": "leg Spin",
    "previousTeam": "",
    "basePrice": "200",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1iST4ZzuJAqFRNwP4y99hCWmAsxvBaa1W"
  },
  {
    "name": "Munsif Ansari ",
    "dateOfBirth": "02-07-1994",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "4.23E+11",
    "classification": "Bowler",
    "roleBowling": "Right Arm Fast Medium",
    "previousTeam": "Galaxy King's 11",
    "basePrice": "200",
    "outsiders ": "yes",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1qzrlmcpcdzTklm-qLvQkCjdC7ZKILVog"
  },
  {
    "name": "Krishna ",
    "dateOfBirth": "15-08-1997",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "4.23E+11",
    "classification": "Wicket keeper",
    "roleBowling": "Right Arm Fast Medium",
    "previousTeam": "RCB",
    "basePrice": "500",
    "outsiders ": "yes",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1-Qspxm_BM6U2g5P5OM5s_L2s1LlsQEHt"
  },
  {
    "name": "Bilal Ahmad ",
    "dateOfBirth": "08-06-2007",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "",
    "classification": "Batsman",
    "roleBowling": "Right Arm Fast Medium",
    "previousTeam": "No",
    "basePrice": "200",
    "outsiders ": "yes",
    "Under19": "yes",
    "imageLink": "https://drive.google.com/file/d/1FUWahbpEC6Km3umQbgNHWxmPdHg8LEuq"
  },
  {
    "name": "Sateesh Kumar ( Teni )",
    "dateOfBirth": "20-08-2007",
    "roleBatting": "",
    "UTRNO": "4.23E+11",
    "classification": "Bowler",
    "roleBowling": "Right Arm Fast Medium",
    "previousTeam": "",
    "basePrice": "300",
    "outsiders ": "",
    "Under19": "yes",
    "imageLink": "https://drive.google.com/file/d/1kVRwHTx2-2ty0GiO-mPAtQzErH6ekdEs"
  },
  {
    "name": "Amit singh ",
    "dateOfBirth": "23-11-1997",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "4.59E+11",
    "classification": "Batsman",
    "roleBowling": "",
    "previousTeam": "Dabang Heroes , Maratha ",
    "basePrice": "500",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1fhJFF99Andr3UAGGsdAWDXjwYVmMMMC9"
  },
  {
    "name": "Vishwa Deepak verma(Chandimal)",
    "dateOfBirth": "03-08-1998",
    "roleBatting": "Opener",
    "UTRNO": "9.13E+11",
    "classification": "Wicket keeper",
    "roleBowling": "",
    "previousTeam": "",
    "basePrice": "500",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1MmrtdgxmxMcDQ0b187o0S2FpueR6-2UB"
  },
  {
    "name": "Saumy Dwivedi (????? ????????) ",
    "dateOfBirth": "07-07-2003",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "4.23E+11",
    "classification": "Batsman",
    "roleBowling": "",
    "previousTeam": "",
    "basePrice": "200",
    "outsiders ": "yes",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1VtR2cse8cnQdNgoZtc2qjOdxf6qMx0AB"
  },
  {
    "name": "Arpit asthana",
    "dateOfBirth": "20-06-2003",
    "roleBatting": "Middle Order batsman",
    "UTRNO": "4.59E+11",
    "classification": "Bowler",
    "roleBowling": "Right Arm Fast Medium",
    "previousTeam": "",
    "basePrice": "200",
    "outsiders ": "yes",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1LeDWn2I-ouiZXo4VDJ3cesK9LT5opcBk"
  },
  {
    "name": "DILEEP SINGH ",
    "dateOfBirth": "1984",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "4.23E+11",
    "classification": "Batsman",
    "roleBowling": "Right Arm Fast Medium",
    "previousTeam": "Dabang Heroes , Warriors ",
    "basePrice": "200",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1d5an49QFHDmheN7tDyRSznbr8RA0oMV6"
  },
  {
    "name": "Nazimudeen",
    "dateOfBirth": "15-08-1996",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "4.23E+11",
    "classification": "All Rounder",
    "roleBowling": "Right Arm Fast Medium",
    "previousTeam": "VEER MARATHA ",
    "basePrice": "200",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1omi51i7nprSBLuepOW6n7QCyjaej-JLE"
  },
  {
    "name": "Shanu akhtar",
    "dateOfBirth": "6=10=1983",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "7.40E+11",
    "classification": "All Rounder",
    "roleBowling": "Right Arm Fast Medium",
    "previousTeam": "",
    "basePrice": "200",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/15v2B67S9tjE0pJD2PP-a4BcHuCRuMtOw"
  },
  {
    "name": "Maanik Maurya",
    "dateOfBirth": "11-11-1996",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "4.60E+12",
    "classification": "All Rounder",
    "roleBowling": "leg Spin",
    "previousTeam": "",
    "basePrice": "200",
    "outsiders ": "yes",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1NXaYTIc0x98dSq3fh2dh-CQPOhqLqO-e"
  },
  {
    "name": "Mohd harun",
    "dateOfBirth": "10-06-1999",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "4.23E+11",
    "classification": "Wicket keeper",
    "roleBowling": "leg Spin",
    "previousTeam": "Shivaji warriors",
    "basePrice": "200",
    "outsiders ": "yes",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/14s3H4qXy_DhUS4qxokUCB3GQlDyyZ40u"
  },
  {
    "name": "Shivam Yadav",
    "dateOfBirth": "14-12-2005",
    "roleBatting": "Left Hand batsman",
    "UTRNO": "5.93E+11",
    "classification": "All Rounder",
    "roleBowling": "Right Arm Fast Medium",
    "previousTeam": "Kesari XI",
    "basePrice": "200",
    "outsiders ": "yes",
    "Under19": "yes",
    "imageLink": "https://drive.google.com/file/d/1QIj9R1j7KCjxzN4h35XpoR8VwVUe1aOE"
  },
  {
    "name": "Shadab Deva",
    "dateOfBirth": "01-01-1996",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "4.23E+11",
    "classification": "All Rounder",
    "roleBowling": "Right Arm Fast Medium",
    "previousTeam": "No",
    "basePrice": "500",
    "outsiders ": "yes",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1ZlnNYeMmnjbv4k5r-xedDfx8EGGRhBIu"
  },
  {
    "name": "Vivek kumar ",
    "dateOfBirth": "04-02-1986",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "4.23E+11",
    "classification": "Batsman",
    "roleBowling": "",
    "previousTeam": "No",
    "basePrice": "200",
    "outsiders ": "yes",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1mT2FMVheR-NthkY9BOXHGBtNA9uIxVB_"
  },
  {
    "name": "Divyansh Pandey",
    "dateOfBirth": "28-10-2006",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "2.50E+11",
    "classification": "Batsman",
    "roleBowling": "",
    "previousTeam": "New",
    "basePrice": "200",
    "outsiders ": "yes",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1Oo3BwEiImpKF3Ep8_ExaaW28N4EGbY0d"
  },
  {
    "name": "Shiv Singh ",
    "dateOfBirth": "04-08-1996",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "4.60E+11",
    "classification": "All Rounder",
    "roleBowling": "Left Arm Fast Medium",
    "previousTeam": "",
    "basePrice": "500",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1p-my0J8kOKZ4cMeT-jC5pY2AD-6Xqy1q"
  },
  {
    "name": "Mohd. Anas",
    "dateOfBirth": "01-01-1991",
    "roleBatting": "Left Hand batsman",
    "UTRNO": "2.20E+11",
    "classification": "All Rounder",
    "roleBowling": "Left Arm Fast Medium",
    "previousTeam": "",
    "basePrice": "200",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1AXKPWdL6thRClm3JKWiRnDbqeH9CuKa6"
  },
  {
    "name": "Arpan Babu ",
    "dateOfBirth": "06-07-1996",
    "roleBatting": "Opener",
    "UTRNO": "4.59E+11",
    "classification": "Batsman",
    "roleBowling": "off spin",
    "previousTeam": "",
    "basePrice": "200",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1_Q76b44XVSuu2t8xz-TKqgM7JF_UhNNx"
  },
  {
    "name": "Aviral Patel",
    "dateOfBirth": "30-09-1999",
    "roleBatting": "Left Hand batsman",
    "UTRNO": "4.23E+11",
    "classification": "All Rounder",
    "roleBowling": "leg Spin",
    "previousTeam": "Veer Maratha ",
    "basePrice": "200",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1Z_RbfZmzEAwTy3Ltk-9vSL_aqM943py-"
  },
  {
    "name": "Mo.Nadeem",
    "dateOfBirth": "01-01-1996",
    "roleBatting": "Middle Order batsman",
    "UTRNO": "4.60E+11",
    "classification": "Wicket keeper",
    "roleBowling": "",
    "previousTeam": "None ",
    "basePrice": "200",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1bVNvaybKV9An9f9MXX-kQfgEzEIYDzNO"
  },
  {
    "name": "Aman Patel ",
    "dateOfBirth": "08-09-2000",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "4.60E+11",
    "classification": "All Rounder",
    "roleBowling": "Right Arm Fast Medium",
    "previousTeam": "Dabang",
    "basePrice": "300",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1kdIPgKy116BY6uJ0GITshyrQWbD4jph0"
  },
  {
    "name": "Bhupendra Kumar ",
    "dateOfBirth": "17-07-1992",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "4.60E+11",
    "classification": "All Rounder",
    "roleBowling": "Right Arm Fast Medium",
    "previousTeam": "Galaxy KING'S ??11",
    "basePrice": "500",
    "outsiders ": "yes",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1iqNN9x8fnbujGFM1GN1I4MlatTk9xqSj"
  },
  {
    "name": "Shashak",
    "dateOfBirth": "10-10-1996",
    "roleBatting": "Left Hand batsman",
    "UTRNO": "4.60E+11",
    "classification": "Bowler",
    "roleBowling": "Right Arm Fast Medium",
    "previousTeam": "Galaxy KING'S ?? 11 ",
    "basePrice": "500",
    "outsiders ": "yes",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1-qlMcAstB7dKufh68uXtGoqUeUvbBB_0"
  },
  {
    "name": "Mo.Sohel ",
    "dateOfBirth": "15-08-2003",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "4.60E+11",
    "classification": "Batsman",
    "roleBowling": "",
    "previousTeam": "None ",
    "basePrice": "200",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/15xnD0fH4a5rXA0mspcWVSerQ4Dhh2ziy"
  },
  {
    "name": "Sangam ",
    "dateOfBirth": "02-10-2006",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "4.60E+11",
    "classification": "Batsman",
    "roleBowling": "",
    "previousTeam": "None ",
    "basePrice": "200",
    "outsiders ": "",
    "Under19": "yes",
    "imageLink": "https://drive.google.com/file/d/1LCwnvGpbNSegNHaaSJPaM2ch9mHfWWju"
  },
  {
    "name": "Mujahid ",
    "dateOfBirth": "01-01-1993",
    "roleBatting": "Middle Order batsman",
    "UTRNO": "4.60E+11",
    "classification": "Batsman",
    "roleBowling": "off spin",
    "previousTeam": "Galaxy King's??11",
    "basePrice": "200",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1nbEU1udho2ZE5Fw7Dz8CRUvH14s3WtLk"
  },
  {
    "name": "Yogendra Singh ",
    "dateOfBirth": "27-07-1996",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "4.60E+11",
    "classification": "Wicket keeper",
    "roleBowling": "",
    "previousTeam": "Galaxy KING'S ?? 11 ",
    "basePrice": "500",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1C4Uz6MLey1sQg3FpulkJHkSi4FphLfqV"
  },
  {
    "name": "Adil",
    "dateOfBirth": "06-03-1997",
    "roleBatting": "",
    "UTRNO": "4.60E+11",
    "classification": "Batsman",
    "roleBowling": "Right Arm Fast Medium",
    "previousTeam": "Galaxy KING'S ?? 11 ",
    "basePrice": "500",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/file/d/1VuDVdfceKmJLjLcAxp67Kauc7R5GZS2i"
  },
  {
    "name": "Brajesh KUMAR",
    "dateOfBirth": "01-01-1995",
    "roleBatting": "Right Hand batsman",
    "UTRNO": "4.59E+11",
    "classification": "Wicket keeper",
    "roleBowling": "Right Arm Fast Medium",
    "previousTeam": "MARATHA'S",
    "basePrice": "500",
    "outsiders ": "",
    "Under19": "",
    "imageLink": "https://drive.google.com/1TOzFppYTnqDcqpVF7Vss_OCeIzHd10-r"
  },
]



// Function to create and populate the list
function createPlayerList(players) {
  // Get the UL element
  const playerList = document.getElementById('playerList');

  // Loop through the array and create list items
  players.forEach(player => {
  
      const li = document.createElement('li');
      // Set the content of the LI element
      const anchor = document.createElement('a');
      anchor.href = `player.html?name=${encodeURIComponent(player?.name||"")}&dateOfBirth=${encodeURIComponent(player?.dateOfBirth||"")}&roleBatting=${encodeURIComponent(player?.roleBatting||"")}&UTRNO=${encodeURIComponent(player?.UTRNO||"")}&classification=${encodeURIComponent(player?.classification||"")}&roleBowling=${encodeURIComponent(player?.roleBowling||"")}&previousTeam=${encodeURIComponent(player?.previousTeam||"")}&basePrice=${player?.basePrice||""}&outsiders=${encodeURIComponent(player?.outsiders||"")}&Under19=${encodeURIComponent(player?.Under19||"")}&imageLink=${encodeURIComponent(player?.imageLink||"")}`;
      anchor.textContent = player.name
      
      // Append the anchor to the LI
      li.appendChild(anchor);
      // Append the LI to the UL
      playerList.appendChild(li);
      
  });
}

// Ensure the DOM is fully loaded before calling the function
document.addEventListener('DOMContentLoaded', () => {
  createPlayerList(playersArray);
});
